apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zo3c8kail-go
  janus-idp.io/tekton: zo3c8kail-go
  backstage.io/kubernetes-id: zo3c8kail-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zo3c8kail-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
