apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: zo3c8kail-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zo3c8kail-go 
  name: zo3c8kail-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: zo3c8kail-go
    weight: 100 
